"""Import books (It can take ~10 minutes)

Revision ID: 80ffb6e091eb
Revises: ab876bd2268c
Create Date: 2022-08-28 16:21:33.650151

"""
import logging

from alembic import op

from app.models import Book, Version
from app.models.book import Language

from migrations.utils import (
    add_ayats,
    add_hadiths,
    session,
)


# revision identifiers, used by Alembic.
revision = '80ffb6e091eb'
down_revision = 'df0373d5db16'
branch_labels = None
depends_on = None

logger = logging.getLogger("alembic.runtime.migration")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    PATH = "./migrations/books"
    books = {
        "quran": {
            Language.AR: f"{PATH}/quran-ar.json",
            Language.EN: f"{PATH}/mustafa-khattab-en.json",
            Language.RU: f"{PATH}/abuadel-ru.json"
        },
        "bukhari": {
            Language.AR: f"{PATH}/bukhari-ar.json",
            Language.EN: f"{PATH}/bukhari-en.json"
        },
        "muslim": {
            Language.AR: f"{PATH}/muslim-ar.json",
            Language.EN: f"{PATH}/muslim-en.json"
        },
        "nasai": {
            Language.AR: f"{PATH}/nasai-ar.json",
            Language.EN: f"{PATH}/nasai-en.json"
        },
        "abudawud": {
            Language.AR: f"{PATH}/abudawud-ar.json",
            Language.EN: f"{PATH}/abudawud-en.json"
        },
        "tirmidhi": {
            Language.AR: f"{PATH}/tirmidhi-ar.json",
            Language.EN: f"{PATH}/tirmidhi-en.json"
        },
        "ibnmajah": {
            Language.AR: f"{PATH}/ibnmajah-ar.json",
            Language.EN: f"{PATH}/ibnmajah-en.json"
        }
    }
    for i, (title, versions) in enumerate(books.items(), 1):
        book = Book(title=title)
        logger.info(f"Import book {i}/{len(books)}: {book.title}")
        for language, path in versions.items():
            version = Version(language=language)
            book.versions.append(version)
            if title == "quran":
                add_ayats(path, book, version)
            else:
                add_hadiths(path, book, version)
        session.add(book)
        session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE book RESTART IDENTITY CASCADE;")
    # ### end Alembic commands ###
