"""Add Complaint table

Revision ID: c413e211f4dc
Revises: d6115cd574e9
Create Date: 2022-05-16 09:13:55.123042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c413e211f4dc'
down_revision = 'd6115cd574e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_topic_id'), 'complaint', ['topic_id'], unique=False)
    op.create_index(op.f('ix_complaint_user_id'), 'complaint', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaint_user_id'), table_name='complaint')
    op.drop_index(op.f('ix_complaint_topic_id'), table_name='complaint')
    op.drop_table('complaint')
    # ### end Alembic commands ###
