"""Add response table

Revision ID: df0373d5db16
Revises: 3416c8647b57
Create Date: 2022-06-24 15:24:09.962111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df0373d5db16'
down_revision = 'f2e3e3659ba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('index_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), server_default="0", nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLIC', name='responsestatus'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.ForeignKeyConstraint(['index_id'], ['index.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_response_topic_id'), 'response', ['topic_id'], unique=False)
    op.create_index(op.f('ix_response_index_id'), 'response', ['index_id'], unique=False)
    op.create_index(op.f('ix_response_user_id'), 'response', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_response_topic_id'), table_name='response')
    op.drop_index(op.f('ix_response_user_id'), table_name='response')
    op.drop_index(op.f('ix_response_index_id'), table_name='response')
    op.drop_table('response')
    # ### end Alembic commands ###
