"""Adde Book associated tables

Revision ID: f2e3e3659ba9
Revises: c413e211f4dc
Create Date: 2022-06-19 17:26:56.131162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f2e3e3659ba9'
down_revision = 'c413e211f4dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_title'), 'book', ['title'], unique=True)
    op.create_table('version',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('language', sa.Enum('AR', 'EN', 'RU', name='language'), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_version_book_id'), 'version', ['book_id'], unique=False)
    op.create_index(op.f('ix_version_language'), 'version', ['language'], unique=False)
    op.create_table('chapter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version_id', sa.Integer()),
    sa.ForeignKeyConstraint(['version_id'], ['version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapter_version_id'), 'chapter', ['version_id'], unique=False)
    op.create_table('text',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('chapter_id', sa.Integer()),
    sa.Column('version_id', sa.Integer()),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_text_chapter_id'), 'text', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_text_version_id'), 'text', ['version_id'], unique=False)
    op.create_table('index',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('chapter_number', sa.SmallInteger(), nullable=False),
    sa.Column('text_number', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_index_chapter_number'), 'index', ['chapter_number'], unique=False)
    op.create_index(op.f('ix_index_text_number'), 'index', ['text_number'], unique=False)
    op.create_index(op.f('ix_index_book_id'), 'index', ['book_id'], unique=False)
    op.create_table('index_chapter',
    sa.Column('index_id', sa.Integer(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ),
    sa.ForeignKeyConstraint(['index_id'], ['index.id'], )
    )
    op.create_table('index_text',
    sa.Column('index_id', sa.Integer(), nullable=True),
    sa.Column('text_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['text_id'], ['text.id'], ),
    sa.ForeignKeyConstraint(['index_id'], ['index.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('index_text')
    op.drop_table('index_chapter')
    op.drop_index(op.f('ix_index_text_number'), table_name='index')
    op.drop_index(op.f('ix_index_chapter_number'), table_name='index')
    op.drop_table('index')
    op.drop_index(op.f('ix_text_number'), table_name='text')
    op.drop_index(op.f('ix_text_chapter_id'), table_name='text')
    op.drop_index(op.f('ix_text_version_id'), table_name='text')
    op.drop_table('text')
    op.drop_index(op.f('ix_chapter_version_id'), table_name='chapter')
    op.drop_index(op.f('ix_chapter_number'), table_name='chapter')
    op.drop_table('chapter')
    op.drop_index(op.f('ix_version_book_id'), table_name='version')
    op.drop_table('version')
    op.drop_index(op.f('ix_book_title'), table_name='book')
    op.drop_table('book')
    # ### end Alembic commands ###
